### ISSUE TITLE
[邀请]字节跳动Flutter PC技术经理岗位

### ISSUE THREAD

**Issue by Sunbreak** [cloudwebrtc/go-sip-ua#1]
我也是武汉人，目前就职于北京字节跳动Flutter PC组

我们目前已经在推进Flutter PC的应用了，比如：
https://github.com/woodemi/Flutter-RTM-Desktop
https://github.com/woodemi/Flutter-SDK-Desktop

每双周和Google同步一次进度，昨天还开会说了Windows打包编译问题，因为飞书已经开始用了

头条薪资绝对丰厚（这个想必有耳闻），北上广深杭、武汉都有分部，疫情期间都飞书远程办公，位置都不是问题

不知道您是否考虑来指导下我们组呢 :)

微信：wk2311007
邮箱：wangkun.sunbreak@bytedance.com

**Comment by cloudwebrtc** [comment]
@Sunbreak 很高兴认识您，看到您的项目似乎是一个RTC 客户端，我能帮上什么忙吗？
