### ISSUE TITLE
Getting PANIC error on startup following "README" instructions about TLS not supported 

### ISSUE THREAD

**Issue by sjmcdowall** [cloudwebrtc/go-sip-ua#3]
Hey gang -- just trying out this example on my Mac OS -- and when I run the example for b2bua I get this PANIC error .. 

`go run examples/b2bua/main.go -c
... Lots of Download messages ...
Start pprof on :6655
[2020-09-11 09:37:42.610]  INFO transport.Layer: begin serve protocols sip_server_ptr=0xc0002240b0 transport_layer_ptr=0xc000254120
[2020-09-11 09:37:42.610]  INFO transport.Protocol: begin listening on UDP 0.0.0.0:5060 protocol_ptr=0xc00020c280 sip_server_ptr=0xc0002240b0 transport_layer_ptr=0xc000254120
[2020-09-11 09:37:42.611]  INFO transport.Protocol: begin listening on TCP 0.0.0.0:5060 protocol_ptr=0xc00007e730 sip_server_ptr=0xc0002240b0 transport_layer_ptr=0xc000254120
[2020-09-11 09:37:42.611] PANIC B2BUA: transport.UnsupportedProtocolError: protocol TLS is not supported
panic: (*logrus.Entry) 0xc000194a80

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000216850, 0xc00019a9c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/sjm/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc000194a10, 0x0, 0xc000069660, 0x1, 0x1)
	/Users/sjm/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xf0
github.com/sirupsen/logrus.(*Entry).Panic(0xc000194a10, 0xc000069660, 0x1, 0x1)
	/Users/sjm/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:325 +0x55
github.com/ghettovoice/gosip/log.(*LogrusLogger).Panic(0xc000202e70, 0xc000069660, 0x1, 0x1)
	/Users/sjm/go/pkg/mod/github.com/ghettovoice/gosip@v0.0.0-20200807105127-dadd6a686e38/log/logrus.go:89 +0x57
github.com/cloudwebrtc/go-sip-ua/pkg/b2bua.NewB2BUA(0xc000000000)
	/Users/sjm/play/b2bua/go-sip-ua/pkg/b2bua/b2bua.go:64 +0x676
main.main()
	/Users/sjm/play/b2bua/go-sip-ua/examples/b2bua/main.go:98 +0x215
exit status 2`

I've done some basic Googling but haven't really hit on what the issue is -- seems pretty fundamental.. 

Thanks for any help!

**Comment by cloudwebrtc** [comment]
You can first comment the tls listen because the tls patch has not been merged into the upstream gosip repo
https://github.com/cloudwebrtc/go-sip-ua/blob/master/pkg/b2bua/b2bua.go#L63
```
if err := endpoint.Listen("tls", "0.0.0.0:5061"); err != nil {
```

**Comment by sjmcdowall** [comment]
Thanks -- so the TCP version isn't needed?  I see a patch in the code area under docs ... is there a way to apply it locally (easily) and have it work?  Thanks!

**Comment by cloudwebrtc** [comment]
Fixed https://github.com/cloudwebrtc/go-sip-ua/commit/313f49c617bccf5aa2641bc2222e7e3aa8e0d1a2
