### ISSUE TITLE
SendRegister() places From URI in Contact field

### ISSUE THREAD

**Issue by brnt** [cloudwebrtc/go-sip-ua#32]
On line 184 of `pkg/ua/ua.go`, the `To` field is currently being set to `profile.URI` (same as the `From` field), but it should probably be changed to:

```go
to := &sip.Address{
    Uri: &recipient,
}
```

or

```go
to := &sip.Address{
    Uri: recipient.Clone(),
}
```
I'd create a pull request, but I'm unsure of how you'd prefer to structure it (with or without `Clone()`).

**Comment by cloudwebrtc** [comment]
>I'd create a pull request, but I'm unsure of how you'd prefer to structure it (with or without Clone()).

If it is copied and used in multiple places, I think Clone is needed. In addition, I am very glad that you can PR.

**Comment by brnt** [comment]
This appears to be fine in the latest commits. Feel free to close.

Also, for anyone else that stumbles across this, placing the same address in both the `To` and `From` fields appears to be standard practice for other soft phones. The usage in `ua.go` is consistent with using this URI as an identifier, rather than connection info.

**Comment by cloudwebrtc** [comment]
I think there is no problem here because the values of the From and To headers in the REGISTER message are all AOR (profile.URI).
The recipient corresponds to the Request-URI in the first line of the SIP message.

**Comment by cloudwebrtc** [comment]
So the correct registration code looks like this
The `recipient` is a SIP URI address without a user. = "sip:127.0.0.1:5060;transport=udp"

```go
        uri, err := parser.ParseUri("sip:100@127.0.0.1:5060")
	if err != nil {
		logger.Error(err) 
	}

	profile := account.NewProfile(uri.Clone(), "goSIP",
		&account.AuthInfo{
			AuthUser: "100",
			Password: "100",
			Realm:    "b2bua",
		},
		1800,
	)

	recipient, err := parser.ParseSipUri("sip:127.0.0.1:5060;transport=udp")
	if err != nil {
		logger.Error(err)
	}

	go ua.SendRegister(profile, recipient, profile.Expires)
```

**Comment by brnt** [comment]
Hmmm ... there's still something not quite right here. The example above works for registration, but not when the server initiates a subsequent INVITE or MESSAGE request. The problem appears to be that `sendRegister()` uses the Profile.Uri for all three of `To`, `From`, and `Contact`. The first two are OK, but `Contact` needs to contain the _actual_ contact info for the client (IP, port, and flags like `transport=udp`). One could argue that the developer should simply use those concrete values for all three fields (by simply updating the value of `uri` in the example above), but I don't think the three values should _have_ to be identical. For example, here's some valid output from Linphone:

```
REGISTER sip:127.0.0.1 SIP/2.0
Via: SIP/2.0/UDP 127.0.0.1:5070;branch=z9hG4bK.L0T4Bkyy0;rport=58273;received=172.17.0.1
From: <sip:yd64j2@127.0.0.1>;tag=QTE4lO2Gp
To: sip:yd64j2@127.0.0.1
CSeq: 21 REGISTER
Call-ID: oR6dQPBKPD
Max-Forwards: 70
Supported: replaces, outbound
Accept: application/sdp
Accept: text/plain
Accept: application/vnd.gsma.rcs-ft-http+xml
Contact: <sip:yd64j2@172.17.0.1:58273;transport=udp>;message-expires=604800;+sip.instance="<urn:uuid:0d0112cd-5841-4751-8a48-950b0a25b445>"
Expires: 600
User-Agent: Linphone Desktop/4.1.1 (belle-sip/1.6.3)
Authorization:  Digest realm="foo.bar.baz", nonce="161241478131700", algorithm=MD5, username="yd64j2",  uri="sip:127.0.0.1", response="XXX", cnonce="XXX", nc=00000001, qop=auth
```

As you can see, the canonical registration URI for the client is `sip:yd64j2@127.0.0.1` but the `Contact` field is re-written with the `received` IP address from the last `Via` header. The client itself knows the port number to add to the `Contact` field.

It's been several years since I've done anything with SIP and it's entirely likely that my memory is fuzzy and I'm making some obvious mistake...what am I missing?

**Comment by brnt** [comment]
Ah, OK. `UserAgent.SendRegister()` populates the `Contact` header from a call to `Profile.Contact()`, which is:

```go
func (p *Profile) Contact() *sip.Address {
	contact := &sip.Address{
		Uri:    p.URI.Clone(),
		Params: sip.NewParams(),
	}
	if p.InstanceID != "nil" {
		contact.Params.Add("+sip.instance", sip.String{Str: p.InstanceID})
	}

	for key, value := range p.ContactParams {
		contact.Params.Add(key, sip.String{Str: value})
	}

	//TODO: Add more necessary parameters.
	//etc: ip:port, transport=udp|tcp, +sip.ice, +sip.instance, +sip.pnsreg,

	return contact
}
```

The comment says it all. The implementation of `Profile.Contact()` is a placeholder that just uses the canonical client ID and remains to be fully implemented. I'll take a look at fleshing that out...
