### ISSUE TITLE
Request: Create a simple client example with digest authentication

### ISSUE THREAD

**Issue by brnt** [cloudwebrtc/go-sip-ua#33]
I'm having a heck of a time getting your `examples/client/main.go` file to successfully register with digest authentication. I did find one likely issue (#32) in the creation of the `REGISTER` message, but there's still something I'm missing. I wonder if instead of wading through SIP dumps and trying to debug the many layers involved, I could instead petition you to write an even simpler client example than is currently present. Something along the lines of:

```go
ua := ua.NewUserAgent(&ua.UserAgentConfig{
	UserAgent: "Go Sip Client/1.0.0",
	SipStack:  stack,
}, logger)

ua.RegisterStateHandler = func(state account.RegisterState) {
	logger.Infof("RegisterStateHandler: user => %s, state => %v, expires => %v", state.Account.AuthInfo.AuthUser, state.StatusCode, state.Expiration)
}

uri, err := parser.ParseUri("sip:100@127.0.0.1:5061")
if err != nil {
	logger.Error(err)
}

profile := account.NewProfile(uri.Clone(), "goSIP",
	&account.AuthInfo{
		AuthUser: "100",
		Password: "blah",
		Realm:    "foo.bar.baz",
	},
	1800,
)

recipient, err := parser.ParseSipUri("sip:127.0.0.1:5060;transport=udp")
if err != nil {
	logger.Error(err)
}

go ua.SendRegister(profile, recipient, profile.Expires)
```

^^ This is my current attempt. The initial `REGISTER` message gets delivered just fine, and the registrar responds with a `401` as expected, along with the `WWW-Authenticate` parameters. However, that response just gets swallowed somewhere inside go-sip-ua or gosip.

P.S. Please feel free to point me at a mailing list or IRC channel if one of those would be more appropriate for this kind of request for help.

Thanks for all the time and effort you've obviously put into go-sip-ua. It's very promising. Good work!

**Comment by brnt** [comment]
P.S. I'm running a [drachtio](https://github.com/davehorton/docker-drachtio-server) Docker container as my registrar for this experiment. Works great with other soft phones.

```sh
docker run -d --rm --name drachtio -p 5060:5060/udp -p 5060:5060/tcp -p 9022:9022/tcp drachtio/drachtio-server drachtio --contact "sip:*;transport=tcp,udp" --loglevel debug
```

**Comment by cloudwebrtc** [comment]
@brnt Thanks for your testing, I have confirmed that this issue is caused by the upgrade of the gosip library.

https://github.com/ghettovoice/gosip/issues/18

I created a simple fix [branch](https://github.com/cloudwebrtc/gosip/commit/dfeb03f6fac1e3fc03a632d4edc2fa67a0092dbd), you can pass the registration test,

**Comment by cloudwebrtc** [comment]
Hey @brnt, A basic registration example has been added here
https://github.com/cloudwebrtc/go-sip-ua/blob/master/examples/register/main.go

**Comment by brnt** [comment]
> Hey @brnt, A basic registration example has been added here
> https://github.com/cloudwebrtc/go-sip-ua/blob/master/examples/register/main.go

Thanks! I'll check it out today.

**Comment by brnt** [comment]
Thanks for the example!
