### ISSUE TITLE
Example UA sends SIP BYE

### ISSUE THREAD

**Issue by chumvan** [cloudwebrtc/go-sip-ua#94]
Hi,
Could anyone share how to send a SIP BYE to a SIP Server using this package? From the example and `ua` in the `pkg`, I can only see the Invite and Register implemented.
Thanks for your help.

**Comment by oogali** [comment]
```
	bye, err := sip.NewRequestBuilder().
		SetMethod("BYE").
		SetContact(contact).
		SetFrom(from).
		SetTo(to).
		SetCallID(callID).
		SetUserAgent(userAgent).
		SetBody("").
		Build()
	if err != nil {
		// ...
	}

	if err := s.Send(bye); err != nil {
		// ...
	}
```

**Comment by chumvan** [comment]
Thank you, @oogali. I guess we need to extend the `ua` package to add this new feature.
